title: Edton de Oliveira Lemos
logo: /assets/img/logo.png
description: Bacharel em Sistemas de Informação. Programador Java. Desenvolvedor Android em construção.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
